// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: entries.sql

package db

import (
	"context"
	"testing"

	"github.com/morgan/simplebank/utils"
	"github.com/stretchr/testify/require"
)

func TestCreatEntry(t *testing.T) {
	acct := createTestAccount()
	arg := CreatEntryParams{
		AccountID: acct.ID,
		Amount: utils.RandomMoney(),
	}
	entry , err:= testQueries.CreatEntry(context.Background(),arg)
	require.NoError(t,err)
	require.NotEmpty(t,entry)
	require.NotEmpty(t,entry.CreatedAt)
	require.Equal(t,acct.ID,entry.AccountID)
}
